exports.groups = [
	'https://t.me/sosalki_spb',
	'https://t.me/vipescortSaintP',
	'https://t.me/EscSochi',
	'https://t.me/EskortSP',
	'https://t.me/babo4ki_moskva',
	'https://t.me/swngmsk',
	'https://t.me/v_teme_moskva',
	'https://t.me/relaxim_msk',
	'https://t.me/keks_nark_rknr',
	'https://t.me/mutki_msk',
	'https://t.me/loveme_msk',
	'https://t.me/OmskOfLove',
	'https://t.me/ESCORTWORK00',
	'https://t.me/intim_escort',
	'https://t.me/EscortRussia0',
	'https://t.me/EscortPeter00',
	'https://t.me/EscortMoscow00',
	'https://t.me/EscortNovosibirsk0',
	'https://t.me/eskort_Russia_dosug',
	'https://t.me/ESKORTs0',	//ban
	'https://t.me/EscortVIP0', //ban
	'https://t.me/workfortoday_msk2', //ban
	'https://t.me/workfortoday_msk1', //ban
	'https://t.me/chat_moskow_escort_msk',
	'https://t.me/eskort_moscov',
	//'https://t.me/ufa_chat102R',
	'https://t.me/EscoRRT36',
	'https://t.me/eskortekbznakomstva',
	//'https://t.me/ekb_eskort96',
	//'https://t.me/eskort_54',
	'https://t.me/escort_secret_chat',
	'https://t.me/escort_secret_moscow',
	//'https://t.me/sponsors_ekb',
	//'https://t.me/soderzhanki_54',
	'https://t.me/soderzhanki11chat',
	'https://t.me/Sodershanka36',
	//'https://t.me/prostitutki_ufa02',
	'https://t.me/znakomstva_spb17',
	'https://t.me/mbr_sex',
	'https://t.me/saltovka_girl',
	'https://t.me/intimcityworld',
	'https://t.me/virtmoneygirl',
	//'https://t.me/escortrf', //не указан город
	'https://t.me/zakazputan',
	'https://t.me/indizon',
	'https://t.me/Eskort_Evrope',
	'https://t.me/intimcityworld',
	'https://t.me/eskort_public',
	'https://t.me/escort_usa_pro',
	'https://t.me/eskort_Russia_dosug',
	//'https://t.me/chat_blag',
	'https://t.me/moskva69sex',
  'https://t.me/seksvirtikmoskva',
	'https://t.me/indisex78',
];